engines:
  eslint:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - _assets/javascript/**
  - _assets/stylesheets/**
exclude_paths:
  - "_assets/javascripts/vendor/jquery.min.js"
  - "_assets/javascripts/vendor/search.min.js"
