engines:
  eslint:
    enabled: true
  scss-lint:
      enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - _assets/javascript/**
  - _assets/stylesheets/**
