# General Info
name: Brightly Colored
url: https://brightlycolored.org
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:year/:month/:title/
exclude:
  ['README.md', 'Rakefile', 'vendor', 'Gemfile.lock', '.asset-cache', 'bin']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Syntax Highlighting
highlighter: rouge

# Server
port: 4000

# Assets
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Markdown Rendering
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Gems
plugins:
  - jekyll-typogrify

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post
      author: timsmith
      custom_type: link
      subtitle:

collections:
  uploads:
    title: Uploads
    output: true

# Webmentions
webmentions:
  username: brightlycolored.org
  cache_bad_uris_for: 7
  html_proofer: true
  throttle_lookups:
    last_month: daily
    last_year: weekly
    older: every 2 months

# Social
social:
  links:
    - https://twitter.com/smithtimmytim
    - https://github.com/smithtimmytim
    - https://www.linkedin.com/in/smithtimmytim
    - https://www.instagram.com/smithtimmytim/
    - https://www.flickr.com/photos/smithtimmytim
    - https://micro.blog/smith
    - https://twitter.com/BrightlyColord

# Imgix
imgix:
  source: brightlycolored.imgix.net
  secure_url_token: xbqVkEuWUQGMJa6e

sizes: '(min-width: 90em) 1300px, (min-width: 70em) 1000px, (min-width: 50em) 750px, (min-width: 31.5em) 500px, 100vw'

srcset:
  - 500
  - 750
  - 1000
  - 1300
