name: The Bold Report - Development
url: http://localhost:4000
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
highlighter: rouge
permalink: /:title
paginate: 20
plugins_dir:  ./_plugins
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-lunr-js-search
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']
timezone: America/Chicago
port: 4000
post:
  extension: md
assets:
  compress:
    css: false
    js: false
  sources:
      - _assets/fonts
      - _assets/javascripts
      - _assets/stylesheets

# Markdown Rendering
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis", "footnotes", "smart"]
