name: The Bold Report
url: http://theboldreport.net
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']
timezone: America/Chicago
port: 4000
post:
  extension: md
page:
  template: _page.txt
  extension: md
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
      - _assets/fonts
      - _assets/javascripts
      - _assets/stylesheets
  gzip: false
authors:
  ttimsmith:
    display_name: Tim Smith
    email: smith@ttimsmith.com
    web: http://ttimsmith.com/
    twitter: ttimsmith
    github: ttimsmith
    bio: 'Designer who codes, blabber mouth, coffee addict.'
