# General Info
name: Development - The Bold Report
url: http://localhost:4000
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:year/:month/:title/
paginate: 10
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', '.asset-cache']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Where Things Are
plugins_dir:  ./_plugins

# Syntax Highlighting
highlighter: rouge

# Server
port: 4000

# Build Info
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
post:
  extension: md

# Markdown Rendering
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: timsmith
