name: The Bold Report
url: http://theboldreport.net
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
markdown: kramdown
pygments: true
permalink: /:year/:month/:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']
timezone: America/Chicago
post:
  extension: md
page:
  template: _page.txt
  extension: md
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
      - _assets/fonts
      - _assets/javascripts
      - _assets/stylesheets
  gzip: false
authors:
  ttimsmith:
    display_name: Tim Smith
    email: smith@ttimsmith.com
    web: http://ttimsmith.com/
    twitter: ttimsmith
    github: ttimsmith
    bio: 'Designer who codes, blabber mouth, coffee addict.'

# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: '_posts'
  siteurl: 'http://theboldreport.net'
  media: 'uploads'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
