# General Info
name: Brightly Colored
url: https://brightlycolored.org
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:year/:month/:title/
exclude: ['README.md', 'Rakefile', 'vendor', 'Gemfile.lock', '.asset-cache', 'bin']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Syntax Highlighting
highlighter: rouge

# Server
port: 4000

# Assets
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Markdown Rendering
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: timsmith
      custom_type: link
      subtitle:

collections:
  uploads:
    title: Uploads
    output: true  
