# General Info
name: Development | Brightly Colored
url: http://localhost:4000
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:year/:month/:title/
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', '.asset-cache']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Where Things Are
plugins_dir:  ./_plugins

# Pagination
pagination:
  enabled: true
  permalink: '/page/:num/'
  sort_reverse: true
  collection: 'posts'
  per_page: 10
  title: 'Page :num'

# Syntax Highlighting
highlighter: rouge

# Server
port: 4200

# Build Info
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
post:
  extension: md
livereload: true

# Markdown Rendering
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: timsmith
      custom_type: link
