name: The Bold Report
description: 'The Bold Report explores the world of design, development, tech, Geek culture, Apple, and more.'
markdown: kramdown
pygments: true
permalink: /:year/:month/:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess']
lunr_excludes: ['feed.xml', 'sitemap.xml']
timezone: America/Chicago
post:
  extension: md
assets:
  js_compressor: uglifier
  css_compressor: sass
authors:
  ttimsmith:
    display_name: Tim Smith
    email: smith@ttimsmith.com
    web: http://ttimsmith.com/
    twitter: ttimsmith
    github: ttimsmith
    bio: 'Designer who codes, blabber mouth, coffee addict.'
