backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "uploads/media"
collections:
  - name: "link_posts"
    label: "Link Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "custom_type", value: "link"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Post Type", name: "custom_type", widget: "hidden", default: "link"}
      - {label: "Link URL", name: "link_url", widget: "string"}
      - {label: "Post Author", name: "author", widget: "string", default: "timsmith" }
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "article_posts"
    label: "Article Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "custom_type", value: "post"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - {label: "Post Type", name: "custom_type", widget: "hidden", default: "post"}
      - {label: "Post Author", name: "author", widget: "string", default: "timsmith" }
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
